spring:
  datasource:
    # ??????????? library_vue_db ??????????
    url: jdbc:mysql://localhost:3306/library_vue_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # ?? MySQL ??? (??? root)
    username: root
    # ?? MySQL ?? (??????????)
    password: root
    # MySQL 8.0+ ? 9.x ??????
    driver-class-name: com.mysql.cj.jdbc.Driver

# ????????????????????????????? 8080
server:
  port: 8080